import {
  Permission,
  AdminPermission,
  AnalyticsPermission,
  AppsPermission,
  AuthPermission,
  ProfilePermission,
  AuditsPermission,
  ProductSetsPermission,
  CountriesPermission,
  ShippingMethodsPermission,
  DepositsPermission,
  SalesPermission,
  CouponsPermission,
  ItemsPermission,
  SchemasPermission,
  CartPermission,
  MediaPermission,
  OrdersPermission,
  PackagesPermission,
  PagesPermission,
  PaymentsPermission,
  PaymentMethodsPermission,
  ProductsPermission,
  SettingsPermission,
  StatusesPermission,
  TagsPermission,
  UsersPermission,
  RolesPermission,
  SeoPermission,
  WebhooksPermission,
  AttributesPermission,
  BannersPermission,
  ConsentsPermission,
} from '../interfaces/Permissions'

export const PERMISSIONS_TREE = {
  Admin: AdminPermission,
  Analytics: AnalyticsPermission,
  Apps: AppsPermission,
  Auth: AuthPermission,
  Profile: ProfilePermission,
  Audits: AuditsPermission,
  Attributes: AttributesPermission,
  Banners: BannersPermission,
  ProductSets: ProductSetsPermission,
  Countries: CountriesPermission,
  ShippingMethods: ShippingMethodsPermission,
  Deposits: DepositsPermission,
  Sales: SalesPermission,
  Coupons: CouponsPermission,
  Consents: ConsentsPermission,
  Items: ItemsPermission,
  Schemas: SchemasPermission,
  Cart: CartPermission,
  Media: MediaPermission,
  Orders: OrdersPermission,
  Packages: PackagesPermission,
  Pages: PagesPermission,
  Payments: PaymentsPermission,
  PaymentMethods: PaymentMethodsPermission,
  Products: ProductsPermission,
  Settings: SettingsPermission,
  Statuses: StatusesPermission,
  Tags: TagsPermission,
  Users: UsersPermission,
  Roles: RolesPermission,
  Seo: SeoPermission,
  Webhooks: WebhooksPermission,
}

export const ALL_PERMISSIONS: Permission[] = Object.values(PERMISSIONS_TREE)
  .map((o) => Object.values(o))
  .flat()
